export { GameObject } from "./classes/GameObject"
export { MonoBehaviour } from "./classes/MonoBehaviour"
export { Ticker } from "./classes/Ticker"
export { clamp } from "./functions/clamp"
export { milliseconds } from "./functions/milliseconds"
export { seconds } from "./functions/seconds"
export type { OnAttach } from "./hooks/OnAttach"
export type { OnDetach } from "./hooks/OnDetach"
export type { OnRender } from "./hooks/OnRender"
export type { OnRequestAnimationFrame } from "./hooks/OnRequestAnimationFrame"
export type { OnUpdate } from "./hooks/OnUpdate"
